-- CreateEnum
CREATE TYPE "SupplyType" AS ENUM ('TAXABLE', 'ZERO_RATED_EXPORT', 'ZERO_RATED_SEZ', 'EXEMPT', 'NIL_RATED', 'NON_GST');

-- AlterTable
ALTER TABLE "Purchase" ADD COLUMN     "reverseCharge" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "PurchaseItem" ADD COLUMN     "cgstAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN     "gstRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "hsnCode" TEXT,
ADD COLUMN     "igstAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN     "itcEligible" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "sgstAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN     "taxableValue" DECIMAL(14,2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Sale" ADD COLUMN     "placeOfSupply" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "supplyType" "SupplyType" NOT NULL DEFAULT 'TAXABLE';

-- AlterTable
ALTER TABLE "SaleItem" ADD COLUMN     "cgstAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN     "gstRate" DECIMAL(5,2) NOT NULL DEFAULT 0,
ADD COLUMN     "hsnCode" TEXT,
ADD COLUMN     "igstAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN     "sgstAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
ADD COLUMN     "taxableValue" DECIMAL(14,2) NOT NULL DEFAULT 0;
